version: '3.2'
services:
  backend1:
      build: ./app
      volumes:
        - '/root/devops-test/app'
  backend2:
      build: ./app
      volumes:
        - '/root/devops-test/app'

  loadbalancer:
      build: ./nginx
      ports:
          - '80:80'
volumes:
  app:
